// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbjsF8xYgBrsKMKcbO1X5L2h_xBBZqcZo',
    appId: '1:953855292044:web:db2ac6cd05324956fb81a9',
    messagingSenderId: '953855292044',
    projectId: 'cipa-care-app',
    authDomain: 'cipa-care-app.firebaseapp.com',
    storageBucket: 'cipa-care-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHIb2-E7IBODCm-AVSBt9DAX2Nv8ifxFk',
    appId: '1:953855292044:android:d7ee5c055a9bf936fb81a9',
    messagingSenderId: '953855292044',
    projectId: 'cipa-care-app',
    storageBucket: 'cipa-care-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAii8XKswnjmfb7UHpQ3mW1oCCb5B2PasQ',
    appId: '1:953855292044:ios:1d45615b5431d93cfb81a9',
    messagingSenderId: '953855292044',
    projectId: 'cipa-care-app',
    storageBucket: 'cipa-care-app.appspot.com',
    iosBundleId: 'com.example.cipaCareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAii8XKswnjmfb7UHpQ3mW1oCCb5B2PasQ',
    appId: '1:953855292044:ios:a358b6efe928cf1cfb81a9',
    messagingSenderId: '953855292044',
    projectId: 'cipa-care-app',
    storageBucket: 'cipa-care-app.appspot.com',
    iosBundleId: 'com.example.cipaCareApp.RunnerTests',
  );
}
